### PR TITLE
Helm chart fixes

### PR DESCRIPTION
**Pull request by perttus**
### Problem

Helm chart has some minor issues

### Solution

Add postgres user for `pg_isready`and fix image `tag` 

### Checklist

- [x] You've [signed-off](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#sign-your-work) your work
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/MarquezProject/marquez/blob/main/CHANGELOG.md#unreleased) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned your `.sql` database schema migration according to [Flyway's naming convention](https://flywaydb.org/documentation/concepts/migrations#naming) (_if relevant_)
- [ ] You've included a [header](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#copyright--license) in any source code files (_if relevant_)

### CODE REVIEW

**Review by wslulciuc — APPROVED** [review]
Thanks, @perttus! 💯

**Comment by wslulciuc** [comment]
@perttus, the changes look great! But, looks like you'll need to [sign your commits](https://github.com/MarquezProject/marquez/pull/2374/checks?check_run_id=10780904157) (you can checkout our [`CONTRIBUTING.md`](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#sign-your-work) for more details)

**Comment by wslulciuc** [comment]
@perttus, need any guidance with the DCO check that's failing? Would be great to get this PR merged!

**Comment by perttus** [comment]
> @perttus, need any guidance with the DCO check that's failing? Would be great to get this PR merged!

should be ok now

**Pull request merged**
