### PR TITLE
Add OL compatibility table

### PR DESCRIPTION
**Pull request by wslulciuc**
### Problem

Closes: https://github.com/MarquezProject/marquez/issues/2483

### Solution

This PR adds a compatibility table to better communicate which version of Marquez supports a given version of OpenLineage.

Screen Shot 2023-05-30 at 12 05 13 PM

### Checklist

- [x] You've [signed-off](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#sign-your-work) your work
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [x] You've updated any relevant documentation (_if relevant_)
- [ ] You've included a one-line summary of your change for the [`CHANGELOG.md`](https://github.com/MarquezProject/marquez/blob/main/CHANGELOG.md#unreleased) (_Depending on the change, this may not be necessary_).
- [ ] You've versioned your `.sql` database schema migration according to [Flyway's naming convention](https://flywaydb.org/documentation/concepts/migrations#naming) (_if relevant_)
- [ ] You've included a [header](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#copyright--license) in any source code files (_if relevant_)

### CODE REVIEW

**Comment by julienledem** [comment]
This looks good to me.
This PR should probably also update the release process to indicate to update this table and how a release goes from recommended to maintenance.

**Comment by wslulciuc** [comment]
Thanks for the suggestion, @julienledem. I've added more details on categories of compatibility and releasing guidelines.

**Comment by merobi-hub** [comment]
Thanks, @wslulciuc , this LGTM, but I'm guessing "unrelease" in this sentence should be "unreleased": `The unrelease version of Marquez is marked `CURRENT` and does not come with any guarantees, but is assumed to remain compatible with OpenLineage, although surprises happen and there maybe rare exceptions`.

**Review by merobi-hub — CHANGES_REQUESTED** [review]
Please see comment.

**Comment by jtandrew** [comment]
@wslulciuc I think this looks great, it shows the details of which version matches to which version.

**Review by merobi-hub — APPROVED** [review]
LG!

**Review by pawel-big-lebowski — APPROVED** [review]

**Pull request merged**
