### PR TITLE
fix issue #332: updated to return JobRunRow

### PR DESCRIPTION
**Pull request by Violet-XiaoWeiHuang**
HI @wslulciuc,
please review this Return JobRunRow on JobRunRowMapper.map(), for  #332 
Tx

### CODE REVIEW

**Comment by wslulciuc** [comment]
@Violet-XiaoWeiHuang, thanks for the help! I noticed the CI build is failing. Are you able to run the following cmd successfully locally on your machine?

```
$ ./gradlew compileJava
```

**Comment by Violet-XiaoWeiHuang** [comment]
No, 
`> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-8-openjdk-amd64 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed`

**Comment by wslulciuc** [comment]
Are you sure you have the JDK installed? see: https://openjdk.java.net/install

**Comment by Violet-XiaoWeiHuang** [comment]
yeah, 
I tried you link to update to install the openjdk. 
When I tried `./gradlew compileJava`, it shows the same issue. I consider my Ubuntu is built on top of W10, I had to use the server to run the test.

I digged further about [JobRun](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/models/JobRun.java) and [JobRunRow](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/models/JobRunRow.java). They have members, I cannot just change the return to `new` [JobRunRow](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/models/JobRunRow.java)

**Comment by wslulciuc** [comment]
> I digged further about JobRun and JobRunRow. They have different members, I cannot just change the return to new JobRunRow

Yeah, updating the return type of the mapper is slightly more involved than a simple class rename. The issue doesn't go into the specifics, but you'd eventually run into complication errors once you renamed the class. We want to make sure any class using the mapper are also update along with your PR.

Let me know if you need help on next steps, or if you got it from here.

**Comment by Violet-XiaoWeiHuang** [comment]
I want continue on it.
I compare the members in JobRunRow() and JobRunRowMapper.map(), some of them are different.
https://github.com/MarquezProject/marquez/blob/99e32853ce9a7f133f62517955eb5415b9eb4a83/src/main/java/marquez/db/models/JobRunRow.java#L33-L41
https://github.com/MarquezProject/marquez/blob/434b2ba30803bff6ce89b84a26e2754190ccb3f3/src/main/java/marquez/db/mappers/JobRunRowMapper.java#L31-L38

How could i deal with them? Thank you.

**Comment by wslulciuc** [comment]
> I compare the members in JobRunRow() and JobRunRowMapper.map(), some of them are different.

@Violet-XiaoWeiHuang: Currently, there are fields in [`JobRun`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/service/models/JobRun.java) that are specific to a job run row (`job_version_uuid`, `row_uuid`, etc). That's not ideal, and they should be removed from `JobRun` and only be contained within a [`JobRunRow`](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/db/models/JobRunRow.java). I'm also realizing, as I'm thinking about the sort of changes required to merge this feature, it's fairly involved and requires knowledge of our DB schema. I personally feel this isn't an issue we are ready to tackle just yet, and one that requires far more detail than is outlined in #332 (mostly likely an epic).

In the meantime, I recommend reviewing our DB schema and app structure (see below). Would you be interested in picking up another issue?

### Resources

* _Marquez Data Model_: https://www.lucidchart.com/documents/view/f918ce01-9eb4-4900-b266-49935da271b8/0
* _Marquez App Structure_: https://docs.google.com/document/d/17qrJNFx5YfFWiSNqd53lMed-YOfjTeZUhkis3rAGbN0

**Comment by wslulciuc** [comment]
@Violet-XiaoWeiHuang: I'm going to close this PR for now, but we'll want add these changes (eventually). Thank you again for helping out and tacking the issue!

**Pull request closed without merging**
