### PR TITLE
Update SchemaLocation field as required in API doc

### PR DESCRIPTION
**Pull request by anandhusk**
This PR updates the  OpenAPI specification of schemaLocation to required.
[Issue](https://github.com/MarquezProject/marquez/issues/1023)

Previously
image
Updated 
image

### CODE REVIEW

**Review by KevinMellott91 — COMMENTED** [review]
@anandhusk thanks for fixing this! I think that you also need to run the "bundle" command linked below, so that the HTML page within the documentation reflects your change.

https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#api-docs

**Comment by henneberger** [comment]
You just need to sign your commit so the DCO plugin passes. Otherwise, it looks great to merge.

**Review by henneberger — APPROVED** [review]

**Comment by anandhusk** [comment]
@KevinMellott91 I ran the bundle command and pushed. It made lots of file difference on  docs/openapi.html.

**Comment by anandhusk** [comment]
@henneberger I force pushed with DCO. I ran the bundle command it made lots of file difference on docs/openapi.html. Is that okay?

**Pull request merged**
