### PR TITLE
Fix incorrect postgressql version

### PR DESCRIPTION
**Pull request by jabbera**
### Problem

No such tag exists for postgressql. This appears to be an accidental change.

### CODE REVIEW

**Comment by collado-mike** [comment]
Thanks for the fix. Can you sign off on the commit using these instructions? https://github.com/MarquezProject/marquez/pull/2089/checks?check_run_id=8015992113 Once signed off, we'll be happy to merge

**Comment by jabbera** [comment]
@collado-mike all set.

**Comment by collado-mike** [comment]
That was fast! 

Looks like DCO is still failing because github is expecting a different e-mail address:
> Expected "Mike [jabbera@users.noreply.github.com](mailto:jabbera@users.noreply.github.com)", but got "Michael Barry [github@barry.io](mailto:github@barry.io)".

Unsure why it has your e-mail address as a `github.com` address, but...
I can go ahead and mark it as passed and merge it. You might check your github settings so that future commits don't have this issue. 

Thanks again for the fix!

**Review by wslulciuc — APPROVED** [review]
Thanks, @jabbera! 💯

**Pull request merged**
