### PR TITLE
Updates openapi to show correct key

### PR DESCRIPTION
**Pull request by frankcash**
Updates openapi to show correct key.  

I tried creating a along the lines of:

```bash
curl -X PUT http://localhost:5000/api/v1/namespaces/data_engineering/jobs/airflow.pim_agg \
  -H 'Content-Type: application/json' \
  -d '{
        "type": "BATCH",
        "inputs": ["frank_dev.items"],
        "outputs": ["frank_dev.items_aggregate"],
        "location": "https://github.com/...",
        "description": "thing.",
        "context": {
          "sql":"INSERT INTO frank_dev.items_aggregate..."
        }
      }'
```

Per the Docs discussion
Screen Shot 2020-04-29 at 9 57 04 AM

This results in an empty sql field when running marquez-web.  To resolve this someone needs to send 

```bash
curl -X PUT http://localhost:5000/api/v1/namespaces/data_engineering/jobs/airflow.pim_agg \
  -H 'Content-Type: application/json' \
  -d '{
        "type": "BATCH",
        "inputs": ["frank_dev.items"],
        "outputs": ["frank_dev.items_aggregate"],
        "location": "https://github.com/...",
        "description": "thing.",
        "context": {
          "SQL":"INSERT INTO frank_dev.items_aggregate..."
        }
      }'
```

Thus I felt it necessary to update the openapi examples

### CODE REVIEW

**Comment by frankcash** [comment]
Alternatively this could be changed here: https://github.com/MarquezProject/marquez-web/blob/493e787aa99ed8bac4b02af2f93091ba1243c138/src/types/api.ts#L37

**Comment by frankcash** [comment]
it looks like circle failed for some reason..?

**Comment by wslulciuc** [comment]
@frankcash The _keys_ for a job context are case-sensitive and wasn't aware that `marquez-web` was strictly looking for `SQL`. Thanks for pointing this out!

> Alternatively this could be changed here: https://github.com/MarquezProject/marquez-web/blob/493e787aa99ed8bac4b02af2f93091ba1243c138/src/types/api.ts#L37

You're correct and maybe support for lower case and upper case keys should be supported in `marquez-web`. That said, storing SQL under the `SQL` key was a convention we decided on at WeWork.

Otherwise PR looks great! Updating the API spec will at least allow the UI to correctly fetch any SQL associated with a job version.

**Comment by wslulciuc** [comment]
> it looks like circle failed for some reason..?

Odd, I kicked off CI and all tests passed. The failed build might be because of a flaky test which I look into.

**Comment by frankcash** [comment]
Happy to help!

**Pull request merged**
