### PR TITLE
Web tags for datasets

### PR DESCRIPTION
**Pull request by phixMe**
Fixes: #849 

image

This adds a tag display for the dataset detail page.

Signed-off-by: Peter Hicks <peter@datakin.com>

### CODE REVIEW

**Review by julienledem — APPROVED** [review]
LGTM

**Comment by phixMe** [comment]
This still needs one small update before getting merged.

**Comment by wslulciuc** [comment]
This looks great, @phixMe! Are there any updates to the PR needed before we can merge?

**Review by phixMe — COMMENTED** [review]
Looks good @wslulciuc

**Comment by wslulciuc** [comment]
Thanks @phixMe for walking me through the minor change in order to get this sweet PR merged!

**Pull request merged**
