### PR TITLE
Column Lineage Linking and sticky tab titles

### PR DESCRIPTION
**Pull request by phixMe**
### Problem
Previously, we had a column lineage link at the top of the dataset. Now that has been moved to the column level and therefore will link to the column directly if available.

Also pegs the titles of jobs and datasets to the top of the drawer as an enhancement to keep context in focus for users of Marquez.

One-line summary: Sticky Titles and column lineage links in the table definition.

image

### Checklist

- [x] You've [signed-off](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#sign-your-work) your work
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've included a one-line summary of your change for the [`CHANGELOG.md`](https://github.com/MarquezProject/marquez/blob/main/CHANGELOG.md#unreleased) (_Depending on the change, this may not be necessary_).
- [ ] You've versioned your `.sql` database schema migration according to [Flyway's naming convention](https://flywaydb.org/documentation/concepts/migrations#naming) (_if relevant_)
- [ ] You've included a [header](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#copyright--license) in any source code files (_if relevant_)

### CODE REVIEW

**Review by wslulciuc — APPROVED** [review]
❤️

**Comment by davidsharp7** [comment]
I like this.  Couple of seriously minor comments

Do we want to be able to navigate back from the column lineage view to the dataset view i.e where you came from?

The dataset description seems rammed up against the border line.  The spacing just looks a little off.

Screenshot 2024-05-01 at 19 45 17

**Comment by phixMe** [comment]
@davidsharp7 Good find on the description, I have rectified that display. 

I think we should modify the back button on the column lineage page to navigate back to the original dataset, or include a link to view the table lineage upon that page. But we'll tackle in another work stream.

**Comment by davidsharp7** [comment]
Cool - yeah agree that's a good plan of attack and we can look at it later.

**Review by davidsharp7 — APPROVED** [review]

**Pull request merged**
