### PR TITLE
Add ssl context

### PR DESCRIPTION
**Pull request by lewiesnyder**
Add SSLContext argument to MarquezClient create method to allow for SSL configurations

Replaces #1305 with a fresh start after feedback.

### CODE REVIEW

**Review by wslulciuc — APPROVED** [review]
LGTM 💯 🥇

**Comment by wslulciuc** [comment]
@lewiesnyder: Minding signing your commit? Otherwise, good to merge!

**Comment by lewiesnyder** [comment]
Trying to sign that merge, having difficulty getting that amend to make it over to this repo

**Comment by lewiesnyder** [comment]
@wslulciuc signed and pushed!

**Comment by wslulciuc** [comment]
@lewiesnyder: Hmm, the DCO check is still not passing. Did you follow [these steps](https://github.com/MarquezProject/marquez/pull/1308/checks?check_run_id=2586893081)?

**Comment by lewiesnyder** [comment]
yeah I just tried those again, still not retry the checks

**Comment by wslulciuc** [comment]
I see. If the commits weren't signed initially, you may have to re-open the PR :pensive:, unfortunately. Mind closing, then reopening your PR? Sorry for the extra hurdle to get these sweet changes merged.

**Comment by lewiesnyder** [comment]
no worries. closing this one and hopefully third time's a charm!

**Pull request closed without merging**
