### PR TITLE
UI: Change color for selected node and edges on graph

### PR DESCRIPTION
**Pull request by tito12**
### Problem

Currently selected node and edges are not stand out from others too much.
Due to proposition from last comment from this PR https://github.com/MarquezProject/marquez/pull/2384

### Solution

Selected node and edges highligthed with primary (green) color which more visible than previous.

image

### Checklist

- [x] You've [signed-off](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#sign-your-work) your work
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've included a one-line summary of your change for the [`CHANGELOG.md`](https://github.com/MarquezProject/marquez/blob/main/CHANGELOG.md#unreleased) (_Depending on the change, this may not be necessary_).
- [ ] You've versioned your `.sql` database schema migration according to [Flyway's naming convention](https://flywaydb.org/documentation/concepts/migrations#naming) (_if relevant_)
- [ ] You've included a [header](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md#copyright--license) in any source code files (_if relevant_)

### CODE REVIEW

**Comment by tito12** [comment]
@howardyoo please take a look and approve if it's what you expect :)

**Comment by howardyoo** [comment]
> @howardyoo please take a look and approve if it's what you expect :)

Tested it and verified! Nice work - the UI now looks more helpful in terms of understanding upstream and downstream dependencies of the job/dataset that was selected. Thank you, @tito12 !

**Review by howardyoo — APPROVED** [review]
LGTM, Approved.

**Comment by wslulciuc** [comment]
@tito12, great work! What will the lineage path color be for failed jobs? That is, will the path be red for jobs with a failed state?

**Comment by howardyoo** [comment]
> @tito12, great work! What will the lineage path color be for failed jobs? That is, will the path be red for jobs with a failed state?

According to this PR, there is no color based on the job's status. However, I think that may be a good idea, to distinguish status based on the color. @tito12 , how difficult would it be to include what Willy described within this PR?

**Comment by tito12** [comment]
First idea was about to make green and red color due state, but it was't possible with current api. That's why I used neutral color with bold style previously and due proposition added green color for selected node and edges. Currently it's not possible to highlight all states on graph with state colors to include it here.  @wslulciuc @howardyoo

**Comment by howardyoo** [comment]
> First idea was about to make green and red color due state, but it wasn't possible with current api. That's why I used neutral color with bold style previously and due proposition added green color for selected node and edges. Currently it's not possible to highlight all states on graph with state colors to include it here. @wslulciuc @howardyoo

Hi @tito12 ,
in the Marquez UI, when displaying the lineage graph, here are the list of API calls:
image

In these calls, notice the 'runs' api call, which retrieves the 'run' information of the currently selected job (https://marquezproject.github.io/marquez/openapi.html#operation/getRun)
image

The run json object has an attribute called 'STATE' which is `COMPLETED` at this time.
The list run-states are mentioned here: https://github.com/MarquezProject/marquez/blob/60581e37282c68a75b9f7bf1deb740d90eebedf0/api/src/main/java/marquez/common/models/RunState.java#L8
which are:

  NEW,
  RUNNING,
  COMPLETED,
  ABORTED,
  FAILED

So, I guess we might be able to use this state to indicate whether the job in question can be colored, so I believe the API does exist to extract that.

As for the datasets (not jobs), the data available might be different.
https://marquezproject.github.io/marquez/openapi.html#operation/deleteDataset is the dataset, and
image
and my take is either we use `lifecycleState` in the version of the dataset (could be CREATE, DROP, TRUNCATE, etc.)
or maybe use `createdByRun -> outputVersions.state` that's shown below.
image

I guess the dataset keeps the 'createdByRun' to show information of the run (job)'s result - so the idea might be that
1) if the dataset has 'createdByRun', look at its `outputVersions.state`.
2) if the result is `COMPLETED`, display it normally
3) however, if the result is `ABORTED` or `FAILED`, then show the dataset as RED (or whatever failure color). This is due to the inference that the job run that was responsible to output this dataset has failed, thus the dataset might also have become invalid.

What do you think?

**Comment by howardyoo** [comment]
I've investigated a little bit into this, but for now, it seems like the way the data is coming from the API, and how the lineage graph does NOT have anything related to 'status' suggests that it is not possible for it to render any `status` (like error conditions) to it. That should be considered as another improvement for the future.

**Pull request merged**
