### PR TITLE
Set default backend port to 8080

### PR DESCRIPTION
**Pull request by wslulciuc**
This PR sets the default port in the UI to match the [default port](https://github.com/MarquezProject/marquez/blob/main/marquez.example.yml#L19) of the Marquez backend when running in `dev` mode.

See https://github.com/MarquezProject/marquez/pull/1576#issuecomment-918819760 for more details about the change.

### CODE REVIEW

**Review by mobuchowski — APPROVED** [review]
We have many places where port 5000 is advertised: https://github.com/MarquezProject/marquez/search?q=5000

Maybe it's worth to clean all of those up?

**Comment by julienledem** [comment]
do we need to update the doc? otherwise looks good me

**Review by julienledem — CHANGES_REQUESTED** [review]
feel free to merge when the related doc is updated

**Review by collado-mike — COMMENTED** [review]
Given the sheer number of places that port 5000 is referenced, maybe it would be easier to get rid of all references to port 8080?

```bash
~/workspace/marquez(main) $ grep -R ":5000" --exclude="./docs/*" --exclude="./venv/*" .
./clients/python/marquez_client/constants.py:DEFAULT_MARQUEZ_URL = 'http://localhost:5000'
./clients/python/tests/test_marquez_client.py:    return MarquezClient(url='http;//localhost:5000')
./clients/python/README.md:client = MarquezClient(url='http://localhost:5000')
./clients/java/README.md:    .baseUrl("http://localhost:5000")
./clients/java/README.md:        .baseUrl("https://localhost:5000")
Binary file ./clients/java/build/classes/java/test/marquez/client/MarquezUrlTest.class matches
./clients/java/src/test/java/marquez/client/MarquezUrlTest.java:  static String basePath = "http://marquez:5000";
./clients/java/src/test/java/marquez/client/MarquezUrlTest.java:    Assertions.assertEquals("http://marquez:5000/namespace/nname/job/jname", url.toString());
./clients/java/src/test/java/marquez/client/MarquezUrlTest.java:        "http://marquez:5000/namespace/s3:%2F%2Fbucket/job/jname", url.toString());
./docker/notebooks/Untitled1.ipynb:    "             .config('openlineage.url', 'http://marquez:5000/api/v1/namespaces/spark_integration/')\n",
./docker/notebooks/openlineage(1).ipynb:    "    .config('openlineage.url', 'http://marquez:5000') \\\n",
./docker/notebooks/Untitled.ipynb:    "    .config('openlineage.url', 'http://marquez:5000/api/v1/namespaces/spark_integration/') \\\n",
./docker/notebooks/.ipynb_checkpoints/openlineage(1)-checkpoint.ipynb:    "    .config('openlineage.url', 'http://marquez:5000') \\\n",
./docker/notebooks/.ipynb_checkpoints/Untitled1-checkpoint.ipynb:      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-036ae2dae264>\"\u001b[0;36m, line \u001b[0;32m8\u001b[0m\n\u001b[0;31m    .config('openlineage.url', 'http://marquez:5000/api/v1/namespaces/spark_integration/\")\u001b[0m\n\u001b[0m                                                                                          ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m EOL while scanning string literal\n"
./docker/notebooks/.ipynb_checkpoints/Untitled1-checkpoint.ipynb:    "             .config('openlineage.url', 'http://marquez:5000/api/v1/namespaces/spark_integration/')\n",
./docker/notebooks/.ipynb_checkpoints/Untitled-checkpoint.ipynb:    "    .config('openlineage.url', 'http://marquez:5000/api/v1/namespaces/spark_integration/') \\\n",
./chart/README.md:* http://localhost:5000/api/v1/namespaces
./spec/openapi.yml:  - url: http://localhost:5000/api/v1
./README.md:To explore metadata via graphql, browse to http://localhost:5000/graphql-playground. The graphql endpoint is currently in _beta_ and is located at http://localhost:5000/api/v1-beta/graphql.
./integrations/airflow/tests/integration/integration.py:client = MarquezClient(url='http://marquez:5000')
./integrations/airflow/tests/integration/docker-compose.yml:    entrypoint: ["./wait-for-it.sh", "marquez:5000", "--", "./entrypoint.sh"]
./integrations/airflow/tests/integration/docker-compose.yml:      - MARQUEZ_URL=http://marquez:5000
./integrations/airflow/tests/integration/docker-compose.yml:      - MARQUEZ_URL=http://marquez:5000
./integrations/airflow/tests/integration/docker-compose.yml:      - "5000:5000"
Binary file ./integrations/airflow/openlineage/__pycache__/constants.cpython-37.pyc matches
./integrations/airflow/build/lib/tests/test_marquez_adapter.py:    os.environ['MARQUEZ_URL'] = "http://marquez:5000"
./integrations/airflow/build/lib/tests/test_marquez_adapter.py:    assert client.url == "http://marquez:5000"
./integrations/airflow/build/lib/tests/test_marquez_adapter.py:    os.environ['OPENLINEAGE_URL'] = "http://ol-api:5000"
./integrations/airflow/build/lib/tests/test_marquez_adapter.py:    assert client.url == "http://ol-api:5000"
./integrations/airflow/build/lib/openlineage/constants.py:DEFAULT_MARQUEZ_URL = 'http://localhost:5000'
Binary file ./integrations/spark/build/classes/java/test/marquez/spark/agent/ArgumentParserTest.class matches
Binary file ./integrations/spark/build/classes/java/test/marquez/spark/agent/SparkContainerIntegrationTest.class matches
Binary file ./integrations/spark/build/classes/java/test/marquez/spark/agent/MarquezContextTest.class matches
./integrations/spark/src/test/java/marquez/spark/agent/SparkContainerIntegrationTest.java:            "spark.openlineage.host=http://marquez:5000",
./integrations/spark/src/test/java/marquez/spark/agent/SparkContainerIntegrationTest.java:            "spark.openlineage.host=http://marquez:5000",
./examples/airflow/marquez.env:MARQUEZ_URL=http://marquez:5000  # The URL of the HTTP backend
./examples/airflow/README.md:MARQUEZ_URL=http://marquez:5000  # The URL of the HTTP backend
./examples/airflow/docker-compose.yml:      - "5000:5000"
```

**Comment by julienledem** [comment]
@wslulciuc did you want to finish this?

**Comment by wslulciuc** [comment]
@julienledem Yeah, different ports are used for the API if you are running the API via the JAR or docker. Let me address the comments so we can merge this PR (that's been around for a while now!)

**Comment by wslulciuc** [comment]
@mobuchowski @collado-mike: When running Marquez via docker, the port [`5000`](https://github.com/MarquezProject/marquez/blob/main/Dockerfile#L23) is exposed. This PR sets the default to [`8080`](https://github.com/MarquezProject/marquez/blob/main/marquez.example.yml#L19) which is used when running the Marquez shadow `jar` and is outlined in [step 2](https://github.com/MarquezProject/marquez#step-2-create-marquezyml) of our configuration. For ports we should:

* Use port `8080` as Marquez should work with the web UI, clients, etc when running the shadow `jar`
* Use port `5000` when running via docker and should be overwritten using `MARQUEZ_PORT`

**Pull request merged**
