### PR TITLE
Bound {namespace} to NamespaceName

### PR DESCRIPTION
**Pull request by pbrahmbhatt3**
Bound {namespace} in path variable of resource files to NamespaceName.

### CODE REVIEW

**Comment by pbrahmbhatt3** [comment]
@wslulciuc Hey. Sorry to bug you so much but I forgot to ad a review tag to this pull request. Could you please review it? Thank you. :)

**Comment by wslulciuc** [comment]
@pbrahmbhatt3: It's not trouble at all. I reviewed your patch, everything looks great! I had to merge recent `master` changes into your branch. Mind formatting your code with:

```
$ ./gradlew spotlessApply
``` 

then pushing the change to your branch? That should fix the failing build and we can get your PR merged!

**Comment by pbrahmbhatt3** [comment]
Sure👍

**Comment by wslulciuc** [comment]
Closes #374

**Pull request merged**
